language: android
jdk: oraclejdk8
dist: trusty

branches:
  only:
  - master
  - develop

env:
 global:
 - ANDROID_API=29
 - ANDROID_BUILD_TOOLS=29.0.3

 before_install:
  - chmod +x gradlew

 android:
     components:
     - tools
     - platform-tools
     - build-tools-$ANDROID_BUILD_TOOLS
     - android-$ANDROID_API
     - extra-google-m2repository
     - extra-android-m2repository
     - addon-google_apis-google-19
     licenses:
     - android-sdk-preview-license-.+
     - android-sdk-license-.+
     - google-gdk-license-.+

jobs:
  include:
    - stage: build
      script:
        - ./gradlew clean build