language: android
jdk: openjdk11
os: linux
dist: trusty

branches:
  only:
    - main
    - develop

env:
  global:
    - ANDROID_API=31
    - ANDROID_BUILD_TOOLS=30.0.3

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-31"
  - yes | sdkmanager "build-tools;30.0.3"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - chmod +x gradlew

jobs:
  include:
    - stage: Build and Test
      script:
        - ./gradlew build